# Generated by Django 5.1.7 on 2025-03-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_address_remove_user_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_relation',
            field=models.CharField(blank=True, choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Spouse', 'Spouse'), ('Friend', 'Friend'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Relative', 'Relative'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
