# Generated by Django 5.1.7 on 2025-03-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_emergency_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Doctor', 'Doctor'), ('Admin', 'Admin')], default='User', max_length=10),
        ),
    ]
